DROP TABLE IF EXISTS T_SESSION;
CREATE TABLE T_SESSION (
  ID                 BIGINT(20) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  USER_ID            BIGINT(20) UNSIGNED             NOT NULL,
  USER_NAME          VARCHAR(100),
  USER_TYPE          VARCHAR(20),
  LOGIN_ACCOUNT      VARCHAR(255),
  LOGIN_AGENT        VARCHAR(255),
  LOGIN_IP           VARCHAR(255),
  TICKET_ID          VARCHAR(255)                    NOT NULL,
  TICKET_CREATE_TIME BIGINT(20) UNSIGNED             NOT NULL,
  TICKET_ACCESS_TIME BIGINT(20) UNSIGNED             NOT NULL,
  CREATED_AT         TIMESTAMP                       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY         VARCHAR(20)                     NOT NULL,
  UPDATED_AT         TIMESTAMP                       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY         VARCHAR(20)                     NOT NULL
)
  DEFAULT CHARSET =UTF8;
/*DROP INDEX UK_SESSION ON T_SESSION;*/
CREATE UNIQUE INDEX UK_SESSION ON T_SESSION (TICKET_ID);

